# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
language: "en-US"
early_access: false
enable_free_tier: true
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: true
  focus_paths:
    - src/manifest.json # Core extension file
    - src/background/* # Background service worker
    - src/content/* # Content scripts
    - src/options/* # Options page
    - src/popup/* # Popup pages
  ignoree_paths:
    - node_modules/*
    - .github/*
    - .vscode/*
    - .gitignore
    - .cpqdevkit
    - package-lock.json
  guidelines:
  - "Verify Manifest V3 compatibility and compliance"
  - "Ensure the extension is compatible with the latest version of Chrome"
  - "Ensure error handling is implemented for all user interactions"
chat:
  auto_reply: true
