# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
language: "en-US"
early_access: false
enable_free_tier: true
reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - src/manifest.json       # Core extension file
    - src/background/*        # Background service worker
    - src/content/*           # Content scripts
    - src/options/*           # Options page
    - src/popup/*             # Popup pages
    - test/*                  # Test files
    - "!node_modules/*"
    - "!.github/*"
    - "!.vscode/*"
    - "!.gitignore"
    - "!.cpqdevkit"
    - "!package-lock.json"
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "master"
      - "coverage"
chat:
  auto_reply: true
