# STUB | GITHUB PAGES CONFIG
theme: jekyll-theme-slate

name: Streamline Tools CI

on: [push, pull_request]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Manifest
        run: npx @wext/manifest-validator manifest.json

      - name: Lint Content Scripts
        run: |
          eslint src/content/**/*.js
          eslint src/background/*.js
<<<<<<< HEAD
          eslint src/options/*.js
          eslint src/popup/*.js
=======
>>>>>>> 7bb2c2c (src fldr rename)

  build-check:
    runs-on: ubuntu-latest
    needs: quality-checks
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
        
      - name: Production build
        run: npm run build