name: Release Drafter

on:
  push:
    tags:
      - 'v*'
  pull_request:
    types: [closed]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml

  publish_release:
    needs: update_release_draft
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref }} --notes-file release-notes.md
